[tool.ruff]
# Same as Black.
line-length = 79
# Assume Python 3.9
target-version = "py39"
# See https://beta.ruff.rs/docs/rules/
select = ["E", "F", "B", "UP", "C90", "RUF", "D"]
# Ignore explicit stacklevel`
ignore = ["B028", "D203", "D205", "D211", "D213"]

[tool.ruff.per-file-ignores]
# Default implementation in abstract methods
"./setup.py" = ["E501"]
"./docs/source/conf.py" = ["E501", "E402"]


[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 15

[tool.black]
line-length = 79

[tool.isort]
profile = "black"
line_length = 79
src_paths = ["rl_equation_solver"]

[tool.pytype]
inputs = ["rl_equation_solver"]
disable = ["pyi-error"]

[tool.mypy]
ignore_missing_imports = true
follow_imports = "silent"
show_error_codes = true
exclude = """(?x)(
    ./setup.py$
    | ./docs/source/conf.py$
  )"""

[tool.pytest.ini_options]
# Deterministic ordering for tests; useful for pytest-xdist.
env = [
	"PYTHONHASHSEED=0"
]

filterwarnings = [
    # Tensorboard warnings
    "ignore::DeprecationWarning:tensorboard",
    # Gymnasium warnings
    "ignore::UserWarning:gymnasium",
]
markers = [
    "expensive: marks tests as expensive (deselect with '-m \"not expensive\"')"
]

[tool.coverage.run]
disable_warnings = ["couldnt-parse"]
branch = false
omit = [
  "tests/*",
  "setup.py",
]

[tool.coverage.report]
exclude_lines = [ "pragma: no cover", "raise NotImplementedError()", "if typing.TYPE_CHECKING:"]
