# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env:
      TERM: xterm-256color
      FORCE_COLOR: 1

    # Skip CI if [ci skip] in the commit message
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest ruff black isort
        python -m pip install .
    - name: Lint with ruff
      run: |
        make lint
    - name: Build the doc
      run: |
        python -m pip install sphinx
        python -m pip install sphinx_rtd_theme
        python -m pip install sphinx-click
        make doc
    - name: Check codestyle
      run: |
        make check-codestyle
    - name: Type check
      run: |
        mypy --install-types
        make mypy
      # skip mypy type check for python3.7 (result is different to all other versions)
      if: "!(matrix.python-version == '3.7')"
    - name: Test with pytest
      run: |
        make pytest
    - name: Code coverage
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install pytest-cov
        python -m pip install .
        python -m  pytest --cov=./ --cov-report=xml:coverage.xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: false
        verbose: true